spring.application.name=fakesocial
# Mostra no console o SQL que o Java está gerando
spring.jpa.show-sql=true

server.port=8081

# 1. Endereço do banco (use o ponto para ser relativo à pasta do projeto)
spring.datasource.url=jdbc:h2:file:./testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# 3. Console (para você testar depois que o Spring ficar ligado)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console